// Generates src/lib/iconsaxGlyphs.ts: the static Iconsax artwork for every
// Material Symbols name listed in scripts/iconsax-map.txt, so
// <Icon name="favorite"> draws Iconsax — the family of the animated icons —
// without shipping the whole library (dev dependency only).
//
//   node scripts/generate-iconsax.mjs
//
// Map format: see the header of scripts/iconsax-map.txt.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const pkg = path.join(root, 'node_modules/iconsax-react/dist/esm')

// Each icon module declares `var Linear = function Linear(_ref) { ... return
// React.createElement(...) }`: evaluate just those with a tiny element
// builder instead of loading React.
const h = (tag, props, ...children) => ({ tag, props: props ?? {}, children: children.flat() })
const React = { createElement: h, Fragment: 'frag' }
const attr = k => k.replace(/[A-Z]/g, c => '-' + c.toLowerCase())
const toSvg = n => {
  if (!n || typeof n !== 'object') return ''
  const inner = n.children.map(toSvg).join('')
  if (n.tag === 'frag') return inner
  const a = Object.entries(n.props).filter(([, v]) => v != null).map(([k, v]) => ` ${attr(k)}="${v === '__C__' ? 'currentColor' : v}"`).join('')
  return `<${n.tag}${a}${inner ? `>${inner}</${n.tag}>` : '/>'}`
}
function variant(name, v) {
  const src = fs.readFileSync(path.join(pkg, `${name}.js`), 'utf-8')
  const m = src.match(new RegExp(String.raw`var ${v} = function ${v}\(_ref\d*\) \{[\s\S]*?\n\};`))
  if (!m) throw new Error(`${name}: no ${v} variant`)
  const fn = new Function('React', `${m[0]}; return ${v}`)(React)
  return toSvg(fn({ color: '__C__' }))
}

// Drawn in the Linear style (1.5 stroke, round caps) for what the free set lacks.
const STROKE = 'stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none"'
const label = t => `<text x="12" y="16" text-anchor="middle" font-size="11" font-weight="700" font-family="inherit" fill="currentColor">${t}</text>`
const CUSTOM = {
  '@circle': `<circle cx="12" cy="12" r="9.25" ${STROKE}/>`,
  '@spinner': `<path d="M12 2.75A9.25 9.25 0 1 1 2.75 12" ${STROKE}/>`,
  '@h1': label('H1'), '@h2': label('H2'), '@h3': label('H3'),
  '@strike': `${label('S')}<path d="M5 12h14" ${STROKE}/>`,
}
const turned = s => `<g transform="rotate(45 12 12)">${s}</g>`
const draw = (isx, v) => CUSTOM[isx] ?? (isx === 'X' ? turned(variant('Add', v)) : variant(isx, v))

const map = fs.readFileSync(path.join(root, 'scripts/iconsax-map.txt'), 'utf-8')
  .split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('#'))
  .map(l => { const [ms, spec] = l.split(/\s+/); return [ms, spec.replace('*', ''), spec.endsWith('*')] })

// [Linear] or [Linear, Bold]
const glyphs = {}
for (const [, isx, bold] of map) {
  const g = (glyphs[isx] ??= [draw(isx, 'Linear')])
  if (bold && g.length === 1 && !CUSTOM[isx]) g.push(draw(isx, 'Bold'))
}

const version = JSON.parse(fs.readFileSync(path.join(root, 'node_modules/iconsax-react/package.json'), 'utf-8')).version
const out = `// Generated by scripts/generate-iconsax.mjs from scripts/iconsax-map.txt — do not edit by hand.
// Iconsax (MIT, iconsax-react ${version}): [Linear, Bold?] inner SVG, 24×24 viewBox, currentColor.
export const GLYPHS: Record<string, readonly string[]> = {
${Object.entries(glyphs).map(([k, v]) => `  ${k.replace(/^@/, '_')}: ${JSON.stringify(v)},`).join('\n')}
}

// Material Symbols name → key in GLYPHS.
export const MATERIAL_TO_ICONSAX: Record<string, string> = {
${map.map(([ms, isx]) => `  ${/^\d/.test(ms) ? `'${ms}'` : ms}: '${isx.replace(/^@/, '_')}',`).join('\n')}
}
`
fs.writeFileSync(path.join(root, 'src/lib/iconsaxGlyphs.ts'), out)
console.log(`${map.length} names → ${Object.keys(glyphs).length} glyphs, ${(out.length / 1024).toFixed(1)} KB`)
